default: &default
  adapter: mysql2
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  encoding: utf8
  username: root
  password:
 
development:
  <<: *default
  database: camp
 
test:
  <<: *default
  database: camp
 
production:
  <<: *default
  database: camp